// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpvvgdwinvgrnlvzztpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwdnZnZHdpbnZncm5sdnp6dHBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMzQwNjcsImV4cCI6MjA1NDcxMDA2N30.K_MrYzRlrxMim9lfq7J3LxNYg4UApIkm96hSvjfePdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);